apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
    env: testing
    dc: IN
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: web
      env: testing
      dc: IN
    template:
      metadata:
        name: web
        labels:
          app: web
          env: testing
          dc: IN
      spec: 
        containers: 
        - name: web-con
          image: 227prajwal/jenkins:v2

  